### ISSUE TITLE
v3_addendum pdf

### ISSUE THREAD

**Issue by wuisiong** [StanleyInnovation/user_materials#2]
Hi, I'm looking for the RMP V3 Interface Guide, which was referenced in the manual. 
Where can I get this interface guide, as well as the v3_addendum pdf (assuming they are different files) ?

**Comment by PatrickHussey** [comment]
We are presently working on the interface guide, but there is a full implementation in the segway_ros package. Look in src/segway; the important files are:
segway_comm.py
segway_data_classes.py
system_defines.py

The addendum for the 220V3 is attached, it only covers the base platform not the onboard PC and sensors in the packages.

[24928-00001 - RMP 220 V3.pdf](https://github.com/StanleyInnovation/user_materials/files/173156/24928-00001.-.RMP.220.V3.pdf)

**Comment by wuisiong** [comment]
Thanks, I'll look at those files you mentioned.
